### ISSUE TITLE
Lookup of roles crashing

### ISSUE THREAD

**Issue by MoralCode** [MoralCode/ClassClockAPI#15]
when accessing protected data from the admin panel, it fails with the following error

```
[2022-11-01 15:27:57 +0000] [9] [ERROR] Error handling request /v0/bellschedules
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/classclock-api-8K7EYNFV/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/root/.local/share/virtualenvs/classclock-api-8K7EYNFV/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/root/.local/share/virtualenvs/classclock-api-8K7EYNFV/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/.local/share/virtualenvs/classclock-api-8K7EYNFV/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/root/.local/share/virtualenvs/classclock-api-8K7EYNFV/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/classclock-api-8K7EYNFV/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/classclock-api-8K7EYNFV/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/classclock-api-8K7EYNFV/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/classclock-api/common/helpers.py", line 433, in wrapper
    return func(*args, **kwargs)
  File "/classclock-api/common/helpers.py", line 378, in decorated
    return func(*args, **kwargs)
  File "/classclock-api/common/helpers.py", line 396, in decorated
    is_admin = check_for_role("admin")
  File "/classclock-api/common/helpers.py", line 292, in check_for_role
    role_names = [r["name"].lower() for r in roles_json]
  File "/classclock-api/common/helpers.py", line 292, in <listcomp>
    role_names = [r["name"].lower() for r in roles_json]
TypeError: string indices must be integers
```

**Comment by MoralCode** [comment]
duplicate of #10
