### ISSUE TITLE
Convert database to SQLite

### ISSUE THREAD

**Issue by MoralCode** [MoralCode/ClassClockAPI#2]
Due to an [issue](https://stackoverflow.com/a/59539260) with closing connections from a connection pool with the latest version of `mysql-connector-python`, the hosting provider seemingly only supporting `virtualenv` and not `pipenv` (or at least without more time and effort than its worth at the moment), and my limited time and patience for dealing with issues, I think it would be best to migrate the ClassClock database to SQLite in preparation for possibly finding a new host (since hosting that is not tied to a DB is often cheaper IIRC).

I have attempted the migration and already have the database in sqlite3 format (thanks to https://github.com/dumblob/mysql2sqlite), but it seems as though I have hit some encoding error, presumably due to the weird way that I was storing UUID's in the database as 16-byte BINARY so that it would be faster than retrieving records with `VARCHAR` primary keys (based on my research at the time it was made). Here is the error for the curious:

```
[2021-02-10 20:57:33 -0800] [545386] [ERROR] Error handling request /v0/schools/
Traceback (most recent call last):
  File "/home/ace/.local/share/virtualenvs/API-pA0gWSxv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/ace/.local/share/virtualenvs/API-pA0gWSxv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: Could not decode to UTF-8 column 'schools_school_id' with text 'R,!��`���Bt'
```
that horrible mess of bytes is supposed to represent the bytes-format UUID of 52 2c 21 a0 ce 60 11 e9 b6 83 02 42 ac 1f 08 74 if it helps.

A big transition like this is probably not a super good use of time, so another possible solution to this would be to find and pay for new web hosting that can host the API and database in a way that works better with the dependencies of this API.

While these issues are present on the `main` branch, I have been making the changes on `dev` since theres quite a few unreleased changes there and if there's going to be a change this major to the hosting of the API, it might as well also be a new release.

**Comment by MoralCode** [comment]
this is probably no longer a reasonable idea now that docker is being used to host the database.
